config/routes.rb
Blocipedia::Application.routes.draw do

  resources :charges, only: [:new, :create]

  devise_for :users

  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  
  belongs_to :wiki
  belongs_to :user

  validates :wiki, presence: true
  validates :user, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
   def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end
  
  def init
    self.role ||= 'standard'
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  
  has_many :collaborators
  has_many :users, through: :collaborators
  
  def public?
    private == false
  end
  
  def collaborator_for(user)
    collaborators.where(user_id: user.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create

    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
   
    # Where the real magic happens
    begin
      charge = Stripe::Charge.create(
        customer: customer.id, # Note -- this is NOT the user_id in the app
        amount: 100_00,
        description: "Blocipedia Membership = #{current_user.email}",
        currency: 'usd'
      )

      if current_user.update_attribute(:role, "premium")
        flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."       
      else
        flash[:success] = "There was an error upgrading your account. Please contact support!"        
      end
      
       redirect_to edit_user_registration_path

      # Stripe will send back CardErrors, with friendly messages
      # when something goes wrong.
      # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
  end

  def new
    @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.name}",
     amount: 100_00
   }
 end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  
  before_action :set_wiki
  respond_to :html, :js
  
  def index
    @users = User.all
  end

  def create
    @collaborator = @wiki.collaborators.build(user_id: params[:user_id])
  

    if @collaborator.save
      flash[:notice] = "Collaborator was added."
    else
      flash[:error] = "There was an error saving your collaborator. Please try again."
    end

    respond_with(@collaborator) do |f|
      f.html { redirect_to wiki_collaborators_path(@wiki) }
    end
  end

    def destroy
    @collaborator = @wiki.collaborators.find(params[:id])
      
    if @collaborator.destroy
      flash[:notice] = "Item was removed."
    else
      flash[:error] = "Item couldn't be deleted. Try again."
    end

    respond_with(@collaborator) do |f|
      f.html { redirect_to wiki_collaborators_path(@wiki)  }
    end
  end

  private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
     @wikis = policy_scope(Wiki)
   end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @pwiki = Wiki.new
  end
  
  def create
     @wiki = Wiki.new(params.require(:wiki).permit(:title, :body))
     if @wiki.save
       flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the wiki. Please try again."
       render :new
     end
  end
    
  def edit
     @wiki = Wiki.find(params[:id])
  end
  
  def update
     @wiki = Wiki.find(params[:id])
     if @wiki.update_attributes(params.require(:wiki).permit(:title, :body))
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the wiki. Please try again."
       render :edit
     end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def markdown_to_html(markdown)
  renderer = Redcarpet::Render::HTML.new
  extensions = {fenced_code_blocks: true}
  redcarpet = Redcarpet::Markdown.new(renderer, extensions)
  (redcarpet.render markdown).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <h4>Update Account!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>
  
  

app/views/collaborators/index.html.erb
Collaborators for <%= @wiki.title %>

<table class="table">
<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td>
      <% if @wiki.collaborators.collect(&:user).include?(user) %>
      <%= link_to "Remove", wiki_collaborator_path(@wiki,  @wiki.collaborator_for(user)), method: :delete, class: "btn btn-success" %>
      <% else %>
      <%= link_to "Add as Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
    <div class="container">
        <ul class="nav nav-tabs">
          <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "About", about_path %></li>
          
          <div class="pull-right user-info">
           <% if current_user %>
            <% unless current_user.premium? %>
            <%= link_to "Upgrade Account", new_charge_path %>
            <% end %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
   </ul>

      
      <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
      
<%= yield %>
      </div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Created by: Neema</p>

app/views/welcome/index.html.erb
<br/>
<center><h1>Blocipedia: Social, Markdown Wikis</h1></center>
<div class="jumbotron">
  <center><h1>Create and share Wikis</h1></center>
</div>

<div class="row">
  <div class="col-md-4">
   
  </div>
  <div class="col-md-4">
     <%= link_to  "Sign Up for Free Account", new_user_registration_path, class: 'btn btn-primary btn' %> 
  </div>
  <div class="col-md-4">
     <% if current_user %>
      <%= link_to  "Sign Up for a Premium Account", new_charge_path, class: 'btn btn-primary btn' %>
    <% else %>
      <%= link_to  "Sign Up for a Premium Account", new_user_session_path, class: 'btn btn-primary btn' %>
    <% end %>
  </div>
</div>

app/views/wikis/_form.html.erb
<% if current_user.role == 'admin' || current_user.role == 'premium' %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
    <%= f.check_box :private %> Private wiki
  <% end %>
</div>
<% end %>

app/views/wikis/edit.html.erb
 <h1>Edit Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% @wikis.each do |wiki| %>
<p><%= link_to wiki.title, wiki %></p>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
 
 <div class="row">
   <div class="col-md-4">
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>
<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<%= link_to "Manage Collaborators", wiki_collaborators_path(@wiki) %>
 <p><%= markdown_to_html @wiki.body %></p>